export const API_URL = 'http://localhost:8081';
export const SIGN_IN = '/api/auth/signin';
export const SIGN_UP = '/api/auth/signup';
export const DASHBORD = '/dashboard';
export const BOOK = '/book';
export const EXCHANGE_BOOK = '/exchange-book';
export const MY_BOOKS = '/my-books';
export const BOOK_REQUEST = '/exchange-books' ;
export const SEND_REQUEST = '/send-request';
